#!/bin/sh
partition=0
format=0
dryrun=0

while getopts 'pfd' OPTION; do
  case "$OPTION" in
    p)
      partition=1
      ;;
    f)
      format=1
      ;;
    d)
      dryrun=1
      ;;
  esac
done
shift $(($OPTIND - 1))

machine=$1

if [ -z "$machine" ]; then
  echo "Usage: $0 [-pfst] <machine>"
  echo "  -p Create partitions"
  echo "  -f Format partitions"
  echo "  -d Dry run the script (display commands only)"
  echo " Example: $0 -pf <darko|spruce>"
  exit 0
fi

source ./commands.sh
source ./secrets/common.env

ssd=$(cat ./secrets/$machine/device)
boot_partition=${ssd}p1
lvm_partition=${ssd}p2

STATE "WIFI" "Setup Wifi"
RUN "wpa_passphrase \"$ssid\" \"$psk\" > /etc/wpa_supplicant.conf"
wireless_interface=`ls /sys/class/ieee80211/*/device/net/`
RUN "wpa_supplicant -B -i$wireless_interface -c/etc/wpa_supplicant.conf"
RUN "while ! ping -c 1 google.com > /dev/null 2>&1; do sleep 3; done"

if [ "$partition" -eq "1" ]; then
  STATE "PART" "Setup partitions"
  RUN "parted -s $ssd -- mklabel gpt"
  RUN "parted -s $ssd -- mkpart ESP fat32 1MB 1GB"
  RUN "parted -s $ssd -- mkpart primary 1GB 100%"
  RUN "parted -s $ssd -- set 1 esp on"

  STATE "CRYP" "Setup drive encryption"
  RUN "cryptsetup luksFormat $lvm_partition"         # Asks for an encryption password
fi

RUN "cryptsetup luksOpen $lvm_partition nixos-enc" # Decrypt partition

if [ "$partition" -eq "1" ]; then
  STATE "VOL " "Setup logical volumes"
  RUN "pvcreate /dev/mapper/nixos-enc"               # LVM Physical volume
  RUN "vgcreate nixos-vg /dev/mapper/nixos-enc"      # Volume Group
  RUN "lvcreate -L 32G -n swap nixos-vg"             # Swap (logical volume)
  RUN "lvcreate -l 100%FREE -n root nixos-vg"        # Root (main) filesystem (logical volume)
fi

if [ "$format" -eq "1" ]; then
  STATE "FORM" "Format partitions"
  RUN "mkfs.vfat -n boot $boot_partition"
  RUN "mkfs.ext4 -F -L nixos /dev/nixos-vg/root"
  RUN "mkswap -q -L swap /dev/nixos-vg/swap"
  RUN "swapon /dev/nixos-vg/swap"
fi

STATE "MNT " "Mount partitions"
RUN "mount /dev/nixos-vg/root /mnt"
RUN "mkdir -p /mnt/boot"
RUN "mount $boot_partition /mnt/boot"

STATE "GEN " "Generate config"
RUN "nixos-generate-config --root /mnt"
STATE "LESS" "Inspect generated hardware-configuration.nix"
less /mnt/etc/nixos/hardware-configuration.nix
STATE "LESS" "Inspect generated configuration.nix"
less /mnt/etc/nixos/configuration.nix

STATE "INST" "Install NixOS (unstable channel)"
WAIT "Install NixOS?"
RUN "nix-channel --add https://nixos.org/channels/nixos-unstable nixos"
RUN "nix-channel --update"
RUN "nixos-install --no-root-password --system ./$machine.nix"

STATE "DONE" "Complete"

