#!/usr/bin/env sh

action=REBUILD
command=test
cleanup=0
while getopts 'hdsyurb' OPTION; do
  case "$OPTION" in
    h)
      echo "Usage: $0 [-hdsur] [commit message]"
      echo "  -h                   this help"
      echo "  -d                   run nix-collect-garbage"
      echo "  -s                   rebuild & switch"
      echo "  -y                   dry run"
      echo "  -u                   upgrade channel and switch"
      echo "  -b                   rebuild & boot"
      echo "  -r [commit message]  release - rebuild & switch, with optional git commit"
      exit 0
      ;;
    d)
      cleanup=1
      ;;
    s)
      action=SWITCH
      command=switch
      ;;
    y)
      command=dry-build
      ;;
    b)
      action=BOOT
      command=boot
      ;;
    u)
      action=UPGRADE
      command=switch
      ;;
    r)
      action=RELEASE
      command=switch
      shift $(($OPTIND - 1))
      commit_msg="$1"

      if [ -z "$commit_msg" ]; then
        git diff-index --quiet HEAD --
        if [ "$?" -eq "0" ]; then
          commit_msg=$(git lo -1 | grep "\(.*\)")
        else
          echo "Can't release with uncommited files."
          exit 1
        fi
      else
        git commit -am "$commit_msg"
      fi

      ;;
  esac
done
shift $(($OPTIND - 1))

test "$1" && commit_msg=$1

machine=$(hostname)

echo "[$action] $machine"

configuration_nix=src/$machine

if [ "$cleanup" = "1" ]; then
  sudo nix-collect-garbage -d
fi

# export NIXOS_LABEL=$(echo $commit_msg | sed -E -e 's/[^a-zA-Z0-9:_\.-]/_/g')
# echo "[LABEL] $NIXOS_LABEL"
[ "$action" = "UPGRADE" ] && sudo nix-channel --update
sudo nixos-rebuild $command -I nixos-config=$configuration_nix
hyprctl reload