#!/usr/bin/env sh

source lib/keepass.sh

action=REBUILD
show_trace=
command=test
cleanup=0
while getopts 'hdsyurbctm' OPTION; do
  case "$OPTION" in
    h)
      echo "Usage: $0 [-hdsur] [commit message/machine]"
      echo "  -h                   this help"
      echo "  -d                   run nix-collect-garbage"
      echo "  -s                   rebuild & switch"
      echo "  -y                   dry run"
      echo "  -u                   upgrade channel and switch"
      echo "  -b                   rebuild & boot"
      echo "  -r [commit message]  release - rebuild & switch, with optional git commit"
      echo "  -m [machine]         Build a different machine from the running one. e.g. sirius/aramid/spruce/sapling"
      echo "  -c                   Diff of changes between latest & prev upgrade"
      echo "  -t                   Show trace"
      exit 0
      ;;
    d)
      cleanup=1
      ;;
    s)
      action=SWITCH
      command=switch
      ;;
    y)
      command=dry-build
      ;;
    b)
      action=BOOT
      command=boot
      ;;
    u)
      action=UPGRADE
      command=switch
      ;;
    c)
      nvd diff $(ls -d1v /nix/var/nix/profiles/system-*-link|tail -n 2)
      exit 0
      ;;
    t)
      show_trace=--show-trace
      ;;
    m)
      command=build
      machine=GET
      ;;
    r)
      action=RELEASE
      command=switch
      shift $(($OPTIND - 1))
      commit_msg="$1"

      if [ -z "$commit_msg" ]; then
        git diff-index --quiet HEAD --
        if [ "$?" -eq "0" ]; then
          commit_msg=$(git lo -1 | grep "\(.*\)")
        else
          echo "Can't release with uncommited files."
          exit 1
        fi
      else
        git commit -am "$commit_msg"
      fi

      ;;
  esac
done
shift $(($OPTIND - 1))

if [ "$machine" = "GET" ]; then
  machine=$1
else
  machine=$(hostname)
  commit_msg=$1
fi

configuration_nix=src/machines/$machine

# Check we have Internet
if ! ping -c 1 google.com > /dev/null 2>&1; then
  # Check we have Wifi credentials
  if [ -f secrets/wifi ]; then
    source secrets/wifi
  else
    passwd=$(cat secrets/password)
    askpass "Enter KeePass password for wifi credentials:"
    keepass_export_wifi
  fi

  echo "[WIFI] Network name (SSID) [$ssid]:"
  read ssid_override
  if [ "$ssid_override" ]; then
    echo "[WIFI] Password (PSK):"
    ssid=ssid_override
    read psk
  fi

  # Add to NetworkManager if not
  nmcli device wifi connect $ssid password $psk
  echo "[WIFI] Connecting..."
  while ! ping -c 1 google.com > /dev/null 2>&1; do sleep 1; done
  rm secrets/wifi # Remove credentials once we're connected
fi

nixos_boot_label=$(echo $commit_msg | sed -E -e 's/[^a-zA-Z0-9:_\.-]/_/g')
[ "$nixos_boot_label" ] && echo "[LABEL] $nixos_boot_label"

# Check if both catppuccin and nixos-hardware channels have been added
if ! sudo nix-channel --list | tr '\n' ' ' | grep -sE 'catppuccin.*nixos-hardware' > /dev/null; then
  sudo nix-channel --add https://github.com/catppuccin/nix/archive/main.tar.gz catppuccin
  sudo nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware
  action=UPGRADE
fi

# Fetch hashed_password and ssh keys unless they already exist
if [ ! -f secrets/hashed_password ] || [ ! -d $HOME/.ssh ]; then
  askpass "Enter KeePass password for hashed_password & .ssh/:"
  keepass_export_hashed_password

  # Export public/private keys for this machine to ~/.ssh/
  mkdir -p $HOME/.ssh
  chmod 700 $HOME/.ssh
  keepass_export_keys $prefix $machine
  keepass_export_keys $prefix $machine github
  keepass_export_keys $prefix $machine gitlab
fi

# Export all public keys to secrets/ for use in src/ssh.nix
for m in spruce sirius aramid; do # TODO: sapling; do
  if [ ! -f secrets/${prefix}_${m}.pub ]; then
    askpass "Enter KeePass password for public key export:"
    keepass_export_key public ${prefix}_${m} secrets/
  fi
done

echo "[$action] $machine"
[ "$cleanup" = "1" ] && sudo nix-collect-garbage -d
[ "$action" = "UPGRADE" ] && sudo nix-channel --update
# NIXOS_LABEL=$NIXOS_LABEL
[ "$nixos_boot_label" ] && label="NIXOS_LABEL=$nixos_boot_label"
sudo $label NIXOS_CONFIG=$(pwd)/$configuration_nix nixos-rebuild $command $show_trace
#                                                           -I nixpkgs=/data/code/nixpkgs # -------^

# Remove password once we're done encrypting drives and accessing KeePass
[ -f secrets/password ] && rm secrets/password