#!/usr/bin/env sh

dryrun=0
source ./commands.sh
source ./secrets/common.env
machine=$(hostname)


DATA=/data      # Duplicated in environment.nix
CODE=$DATA/code # Duplicated in environment.nix

STATE 'INIT'

# Copy .ssh/
if [ ! -d "$HOME/.ssh" ]; then
  cp -r secrets/$machine/ssh $HOME/.ssh
  chmod 700 $HOME/.ssh
  chmod 644 $HOME/.ssh/id_rsa.pub
  chmod 600 $HOME/.ssh/id_rsa $HOME/.ssh/known_hosts
fi

# Setup Wifi if not already
RUN "ping -c 1 google.com > /dev/null 2>&1 || sudo iwctl --passphrase=$psk station wlan0 connect $ssid"

# Pull down git repos unless they exist
sudo mkdir -p $DATA
sudo chown phil:users $DATA
mkdir -p $CODE
git_clone() {
  [ -d "$CODE/$1" ] || git clone git@github.com:PhilT/$1.git $CODE/$1
}

git_clone 'nixos-files'
git_clone 'matter'
git_clone 'cv_builder'
git_clone 'vim-fsharp'
git_clone 'sheetzi'

# Copy secrets
cp -r secrets/* $CODE/nixos-files/secrets
find $CODE/nixos-files/secrets -type d -print0 | xargs -0 chmod 755
find $CODE/nixos-files/secrets -type f -print0 | xargs -0 chmod 644