#!/usr/bin/env sh

dryrun=0
source ./commands.sh
source ./secrets/common.env
machine=$(hostname)

# Duplicated in environment.nix
DATA=/data
CODE=$DATA/code

STATE 'INIT'

# Copy .ssh/
if [ ! -d "$HOME/.ssh" ]; then
  cp -r secrets/$machine/ssh $HOME/.ssh
  chmod 700 $HOME/.ssh
  chmod 644 $HOME/.ssh/id_rsa.pub
  chmod 600 $HOME/.ssh/id_rsa $HOME/.ssh/known_hosts
fi

# Setup Wifi if not already
RUN "ping -c 1 google.com > /dev/null 2>&1 || sudo iwctl --passphrase=$psk station wlan0 connect $ssid"

# Pull down git repos unless they exist
sudo mkdir -p $DATA
chown phil:users $DATA
mkdir -p $CODE
git_clone() {
  [ -d "$CODE/$1" ] || git clone git@github.com:PhilT/$1.git $CODE/$1
}

git_clone 'nixos-files'
git_clone 'matter'
git_clone 'dwm'
git_clone 'cv_builder'
git_clone 'vim-fsharp'
git_clone 'sheetzi'

# Copy secrets
cp -r secrets $CODE/nixos-files/
find $CODE/nixos-files/secrets -type d -print0 | xargs -0 chmod 755
find $CODE/nixos-files/secrets -type f -print0 | xargs -0 chmod 644

# Add bluetooth devices
pair_and_trust() {
  bluetoothctl pair $1
  bluetoothctl trust $1
}
bluetoothctl power on

echo "Ensure all bluetooth devices are on and in pairing mode (if applicable)"
echo "E.g. headphones (Sony, mifo, Shokz), HTC lighthouses"
echo "Press ENTER when ready"
read

WH1000XM3=CC:98:8B:93:74:BF
mifo_O5=19:04:31:79:04:ED
LIGHTHOUSE_B=40:4E:36:B9:C1:E5
LIGHTHOUSE_C=40:4E:36:B9:CB:2E
OPEN_RUN_PRO=C0:86:B3:80:58:9A

pair_and_trust $WH1000XM3
pair_and_trust $mifo_O5
pair_and_trust $LIGHTHOUSE_B
pair_and_trust $LIGHTHOUSE_C
pair_and_trust $OPEN_RUN_PRO