#!/bin/sh

action=REBUILD
cleanup=0
while getopts 'hdr' OPTION; do
  case "$OPTION" in
    h)
      echo "Usage: $0 [-dr] [commit message]"
      echo "  -d                   run nix-collect-garbage"
      echo "  -r [commit message]  rebuild & switch, with optional git commit"
      exit 0
      ;;
    d)
      cleanup=1
      ;;
    r)
      action=RELEASE
      shift $(($OPTIND - 1))
      commit_msg="$1"

      if [ -z "$commit_msg" ]; then
        git diff-index --quiet HEAD --
        if [ "$?" -eq "0" ]; then
          commit_msg=$(git lo -1 | grep "\(.*\)")
        else
          echo "Can't release with uncommited files."
          exit 1
        fi
      else
        git commit -am "$commit_msg"
      fi

      ;;
  esac
done

if [ -z "$machine" ]; then
  machine=$(hostname)
fi

if [ "$machine" != "darko" ] && [ "$machine" != "spruce" ]; then
  echo "Machine name not recognised, use `hostname <darko|spruce>` to set"
  exit
fi

source src/common.env
source src/$machine.env

echo "[$action] $machine"

configuration_nix=src/$machine.nix
./copy_config.sh $machine 0 # 0 - No dryrun

if [ "$cleanup" = "1" ]; then
  sudo nix-collect-garbage -d
fi

if [ -z "$commit_msg" ]; then
  sudo nixos-rebuild test -I nixos-config=$configuration_nix
else
  BOOT_LABEL=$(echo $commit_msg | sed -E -e 's/[^a-zA-Z0-9:_\.-]/_/g')
  sudo sed -i "s|BOOT_LABEL|$BOOT_LABEL|" src/minimal.nix

  sudo echo "[LABEL] $BOOT_LABEL"
  sudo nixos-rebuild switch -I nixos-config=$configuration_nix
fi

