#!/usr/bin/env sh

source lib/keepass.sh

# Generates SSH keys and adds them to KeePass

# authorized_keys is what sshd accepts as incoming requests.
# known_hosts is what an ssh client knows about when connecting to
askpass "Enter database password:"

for machine in spruce sirius aramid sapling; do
  for service in home github gitlab; do
    [ "$service" == "home" ] && name=$machine || name=${machine}_$service
    keyfile=${prefix}_$name

    if keepass_exists $keyfile; then
      echo $keyfile exists
    else
      # Generate SSH key with best encryption (ed25519 is the default anyway)
      # and 100 rounds (a bit slower but more secure).
      ssh-keygen -q -t ed25519 -a 100 -f secrets/$keyfile -N ""
      keepass_create $keyfile
      keepass_import_keys $keyfile
      rm secrets/$keyfile
      rm secrets/${keyfile}.pub
      echo $keyfile created
    fi
  done
done