#!/usr/bin/env sh

unmount=1

while getopts 'u' OPTION; do
  case "$OPTION" in
    u)
      unmount=0
      ;;
  esac
done

if [ ! -d /run/media/phil/nixos-data ]; then
  echo "ERROR: Can't find nixos-data USB stick. Aborting."
  exit 1
fi

mkdir -p /run/media/phil/nixos-data/nixos-files
cp /data/sync/HomeDatabase.kdbx /run/media/phil/nixos-data/
rsync -a --exclude=result . /run/media/phil/nixos-data/nixos-files
[ "$unmount" -eq "1" ] && umount /run/media/phil/nixos-data